return PlaceObj('ModDef', {
	'title', "Start Hidden Mod",
	'description', "Start with all squad member hidden when entering a map.\n\nLicense: MIT\nSource Code: https://github.com/Christian1984/jagged-alliance-3-start-hidden-mod",
	'image', "Images/modicon.png",
	'last_changes', "Initial Release",
	'id', "StartHiddenMod",
	'content_path', "Mod/StartHiddenMod/",
	'author', "ChrisVomRhein",
	'version_major', 1,
	'version', 0,
	'lua_revision', 233360,
	'saved_with_revision', 338408,
	'code', {
		"Code/StartHiddenModScript.lua",
	},
	'has_options', true,
	'saved', 1690652575,
	'code_hash', -4373319759099573401,
	'screenshot1', "Images/start-hidden-mod-screenshot-1.png",
	'screenshot2', "Images/start-hidden-mod-screenshot-2.png",
})